# Generated by Django 3.2.7 on 2021-09-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True)),
                ('descricao', models.TextField(default=models.CharField(max_length=150, null=True))),
                ('data_inicial', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Ouvinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('password', models.CharField(blank=True, max_length=16)),
                ('email', models.CharField(default=None, max_length=249)),
                ('confirmado', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ouvinte',
                'verbose_name_plural': 'Ouvintes',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('profissao', models.CharField(max_length=50)),
                ('onde_trabalha', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(default='Admin', max_length=50)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atração', models.IntegerField(choices=[(1, 'Palestra'), (2, 'Workshop'), (3, 'Encontro'), (4, 'Seminário'), (5, 'Mesa-redonda'), (6, 'Simpósio'), (7, 'Painel'), (8, 'Fórum'), (9, 'Conferência'), (10, 'Jornada'), (11, 'Cursos'), (12, 'Colóquio'), (13, 'Semana')], default=1)),
                ('nome', models.CharField(max_length=150, null=True)),
                ('descricao', models.TextField(null=True)),
                ('data', models.DateField(null=True)),
                ('local', models.CharField(default='IFSP JCR', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
                ('palestrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.palestrante')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
                'ordering': ('-created',),
            },
        ),
    ]
