# Generated by Django 3.2.7 on 2021-10-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(default='Insira a descrição'),
        ),
    ]
