# Generated by Django 3.2.7 on 2021-09-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvinte',
            name='confirmado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ouvinte',
            name='password',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
