# Generated by Django 3.2.7 on 2021-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210915_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvinte',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
