# Generated by Django 3.2.7 on 2021-09-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ouvinte_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('data', models.DurationField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('profissao', models.CharField(blank=True, max_length=50)),
                ('onde_trabalha', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ouvinte',
            options={'ordering': ('-created',), 'verbose_name': 'Ouvinte', 'verbose_name_plural': 'Ouvintes'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('-created',), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Palestra'), (2, 'Workshop'), (3, 'Encontro'), (4, 'Seminário'), (5, 'Mesa-redonda'), (6, 'Simpósio'), (7, 'Painel'), (8, 'Fórum'), (9, 'Conferência'), (10, 'Jornada'), (11, 'Cursos'), (12, 'Colóquio'), (13, 'Semana')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('data', models.DateField()),
                ('local', models.CharField(default='IFSP JCR', max_length=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
                ('palestrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.palestrante')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
                'ordering': ('-created',),
            },
        ),
    ]
