# Generated by Django 3.2.7 on 2021-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210923_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='onde_trabalha',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='palestrante',
            name='profissao',
            field=models.CharField(max_length=50),
        ),
    ]
