# Generated by Django 3.2.7 on 2021-11-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ouvinte_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouvinte',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ouvinte',
            name='password',
        ),
    ]
