# Generated by Django 3.2.7 on 2021-11-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211125_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvinte',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
