# Generated by Django 3.2.7 on 2021-09-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_evento_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data',
            new_name='data_final',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
