# Generated by Django 3.2.7 on 2021-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_ouvinte_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvinte',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=249, null=True),
        ),
    ]
