# Generated by Django 3.2.7 on 2021-09-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210923_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='type',
            new_name='atração',
        ),
    ]
